-- Seed script for visualizer_presets table
-- Auto-generated from butterchurn-presets package
-- Inserts all presets with display_name = original_name

INSERT INTO public.visualizer_presets (original_name, display_name)
VALUES
  ('$$$ Royal - Mashup (197)', '$$$ Royal - Mashup (197)'),
  ('$$$ Royal - Mashup (220)', '$$$ Royal - Mashup (220)'),
  ('$$$ Royal - Mashup (431)', '$$$ Royal - Mashup (431)'),
  ('_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)', '_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)'),
  ('_Geiss - Artifact 01', '_Geiss - Artifact 01'),
  ('_Geiss - Desert Rose 2', '_Geiss - Desert Rose 2'),
  ('_Geiss - untitled', '_Geiss - untitled'),
  ('_Mig_049', '_Mig_049'),
  ('_Mig_085', '_Mig_085'),
  ('_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)', '_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)'),
  ('Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix', 'Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix'),
  ('Aderrasi - Potion of Spirits', 'Aderrasi - Potion of Spirits'),
  ('Aderrasi - Songflower (Moss Posy)', 'Aderrasi - Songflower (Moss Posy)'),
  ('Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics', 'Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics'),
  ('An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B', 'An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B'),
  ('cope + martin - mother-of-pearl', 'cope + martin - mother-of-pearl'),
  ('Cope - The Neverending Explosion of Red Liquid Fire', 'Cope - The Neverending Explosion of Red Liquid Fire'),
  ('Eo.S. + Phat - cubetrace - v2', 'Eo.S. + Phat - cubetrace - v2'),
  ('Eo.S. + Zylot - skylight (Stained Glass Majesty mix)', 'Eo.S. + Zylot - skylight (Stained Glass Majesty mix)'),
  ('Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b', 'Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b'),
  ('fiShbRaiN + Flexi - witchcraft 2.0', 'fiShbRaiN + Flexi - witchcraft 2.0'),
  ('flexi + amandio c - organic [random mashup]', 'flexi + amandio c - organic [random mashup]'),
  ('flexi + amandio c - organic12-3d-2.milk', 'flexi + amandio c - organic12-3d-2.milk'),
  ('Flexi + amandio c - piercing 05 - Kopie (2) - Kopie', 'Flexi + amandio c - piercing 05 - Kopie (2) - Kopie'),
  ('flexi + fishbrain - neon mindblob grafitti', 'flexi + fishbrain - neon mindblob grafitti'),
  ('flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]', 'flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]'),
  ('Flexi + Martin - astral projection', 'Flexi + Martin - astral projection'),
  ('Flexi + Martin - cascading decay swing', 'Flexi + Martin - cascading decay swing'),
  ('Flexi + stahlregen - jelly showoff parade', 'Flexi + stahlregen - jelly showoff parade'),
  ('Flexi - alien fish pond', 'Flexi - alien fish pond'),
  ('Flexi - area 51', 'Flexi - area 51'),
  ('flexi - bouncing balls [double mindblob neon mix]', 'flexi - bouncing balls [double mindblob neon mix]'),
  ('Flexi - infused with the spiral', 'Flexi - infused with the spiral'),
  ('Flexi - mindblob [shiny mix]', 'Flexi - mindblob [shiny mix]'),
  ('Flexi - mindblob mix', 'Flexi - mindblob mix'),
  ('flexi - mom, why the sky looks different today', 'flexi - mom, why the sky looks different today'),
  ('flexi - patternton, district of media, capitol of the united abstractions of fractopia', 'flexi - patternton, district of media, capitol of the united abstractions of fractopia'),
  ('Flexi - predator-prey-spirals', 'Flexi - predator-prey-spirals'),
  ('Flexi - smashing fractals [acid etching mix]', 'Flexi - smashing fractals [acid etching mix]'),
  ('flexi - swing out on the spiral', 'flexi - swing out on the spiral'),
  ('Flexi - truly soft piece of software - this is generic texturing (Jelly) ', 'Flexi - truly soft piece of software - this is generic texturing (Jelly) '),
  ('flexi - what is the matrix', 'flexi - what is the matrix'),
  ('Flexi, fishbrain, Geiss + Martin - tokamak witchery', 'Flexi, fishbrain, Geiss + Martin - tokamak witchery'),
  ('Flexi, martin + geiss - dedicated to the sherwin maxawow', 'Flexi, martin + geiss - dedicated to the sherwin maxawow'),
  ('Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b', 'Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b'),
  ('Geiss + Flexi + Martin - disconnected', 'Geiss + Flexi + Martin - disconnected'),
  ('Geiss - Cauldron - painterly 2 (saturation remix)', 'Geiss - Cauldron - painterly 2 (saturation remix)'),
  ('Geiss - Reaction Diffusion 2', 'Geiss - Reaction Diffusion 2'),
  ('Geiss - Spiral Artifact', 'Geiss - Spiral Artifact'),
  ('Geiss - Thumb Drum', 'Geiss - Thumb Drum'),
  ('Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]', 'Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]'),
  ('Goody - The Wild Vort', 'Goody - The Wild Vort'),
  ('high-altitude basket unraveling - singh grooves nitrogen argon nz+', 'high-altitude basket unraveling - singh grooves nitrogen argon nz+'),
  ('Idiot - Star Of Annon', 'Idiot - Star Of Annon'),
  ('Krash + Illusion - Spiral Movement', 'Krash + Illusion - Spiral Movement'),
  ('martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained', 'martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained'),
  ('Martin - acid wiring', 'Martin - acid wiring'),
  ('martin - angel flight', 'martin - angel flight'),
  ('martin - another kind of groove', 'martin - another kind of groove'),
  ('martin - bombyx mori', 'martin - bombyx mori'),
  ('martin - castle in the air', 'martin - castle in the air'),
  ('martin - chain breaker', 'martin - chain breaker'),
  ('Martin - charisma', 'Martin - charisma'),
  ('martin - disco mix 4', 'martin - disco mix 4'),
  ('martin - extreme heat', 'martin - extreme heat'),
  ('martin - frosty caves 2', 'martin - frosty caves 2'),
  ('martin - fruit machine', 'martin - fruit machine'),
  ('martin - ghost city', 'martin - ghost city'),
  ('martin - glass corridor', 'martin - glass corridor'),
  ('martin - infinity (2010 update)', 'martin - infinity (2010 update)'),
  ('Martin - liquid arrows', 'Martin - liquid arrows'),
  ('martin - mandelbox explorer - high speed demo version', 'martin - mandelbox explorer - high speed demo version'),
  ('martin - mucus cervix', 'martin - mucus cervix'),
  ('Martin - QBikal - Surface Turbulence IIb', 'Martin - QBikal - Surface Turbulence IIb'),
  ('martin - reflections on black tiles', 'martin - reflections on black tiles'),
  ('martin - stormy sea (2010 update)', 'martin - stormy sea (2010 update)'),
  ('martin - The Bridge of Khazad-Dum', 'martin - The Bridge of Khazad-Dum'),
  ('martin - witchcraft reloaded', 'martin - witchcraft reloaded'),
  ('martin [shadow harlequins shape code] - fata morgana', 'martin [shadow harlequins shape code] - fata morgana'),
  ('martin, flexi, fishbrain + sto - enterstate [random mashup]', 'martin, flexi, fishbrain + sto - enterstate [random mashup]'),
  ('Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX', 'Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX'),
  ('ORB - Waaa', 'ORB - Waaa'),
  ('Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix', 'Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix'),
  ('Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)', 'Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)'),
  ('Rovastar - Oozing Resistance', 'Rovastar - Oozing Resistance'),
  ('sawtooth grin roam', 'sawtooth grin roam'),
  ('shifter - dark tides bdrv mix 2', 'shifter - dark tides bdrv mix 2'),
  ('suksma - heretical crosscut playpen', 'suksma - heretical crosscut playpen'),
  ('suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression', 'suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression'),
  ('suksma - uninitialized variabowl (hydroponic chronic)', 'suksma - uninitialized variabowl (hydroponic chronic)'),
  ('suksma - vector exp 1 - couldn′t not', 'suksma - vector exp 1 - couldn′t not'),
  ('TonyMilkdrop - Leonardo Da Vinci''s Balloon [Flexi - merry-go-round + techstyle]', 'TonyMilkdrop - Leonardo Da Vinci''s Balloon [Flexi - merry-go-round + techstyle]'),
  ('TonyMilkdrop - Magellan''s Nebula [Flexi - you enter first + multiverse]', 'TonyMilkdrop - Magellan''s Nebula [Flexi - you enter first + multiverse]'),
  ('Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)', 'Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)'),
  ('Unchained - Rewop', 'Unchained - Rewop'),
  ('Unchained - Unified Drag 2', 'Unchained - Unified Drag 2'),
  ('yin - 191 - Temporal singularities', 'yin - 191 - Temporal singularities'),
  ('Zylot - Paint Spill (Music Reactive Paint Mix)', 'Zylot - Paint Spill (Music Reactive Paint Mix)'),
  ('Zylot - Star Ornament', 'Zylot - Star Ornament'),
  ('Zylot - True Visionary (Final Mix)', 'Zylot - True Visionary (Final Mix)')
ON CONFLICT (original_name) DO NOTHING;
