-- Seed script for visualizer_presets table
-- Updates all Butterchurn presets with cool one-word display names
-- Re-running is safe: uses upsert on original_name

INSERT INTO public.visualizer_presets (original_name, display_name)
VALUES
  ('$$$ Royal - Mashup (197)', 'Prometheus'),
  ('$$$ Royal - Mashup (220)', 'Xenophage'),
  ('$$$ Royal - Mashup (431)', 'Stareater'),
  ('_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)', 'Bareback'),
  ('_Geiss - Artifact 01', 'Wraith'),
  ('_Geiss - Desert Rose 2', 'Cinder'),
  ('_Geiss - untitled', 'Hexglass'),
  ('_Mig_049', 'Voidcaller'),
  ('_Mig_085', 'Morphine'),
  ('_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)', 'Tachyon'),
  ('Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix', 'Slipstream'),
  ('Aderrasi - Potion of Spirits', 'Cathedral'),
  ('Aderrasi - Songflower (Moss Posy)', 'Bonecrush'),
  ('Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics', 'Nightshade'),
  ('An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B', 'Quasar'),
  ('cope + martin - mother-of-pearl', 'Drift'),
  ('Cope - The Neverending Explosion of Red Liquid Fire', 'Eclipse'),
  ('Eo.S. + Phat - cubetrace - v2', 'Magnetar'),
  ('Eo.S. + Zylot - skylight (Stained Glass Majesty mix)', 'Saltflame'),
  ('Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b', 'Reverie'),
  ('fiShbRaiN + Flexi - witchcraft 2.0', 'Venom'),
  ('flexi + amandio c - organic [random mashup]', 'Torque'),
  ('flexi + amandio c - organic12-3d-2.milk', 'Obsidian'),
  ('Flexi + amandio c - piercing 05 - Kopie (2) - Kopie', 'Fracture'),
  ('flexi + fishbrain - neon mindblob grafitti', 'Neonspine'),
  ('flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]', 'Terminus'),
  ('Flexi + Martin - astral projection', 'Astral'),
  ('Flexi + Martin - cascading decay swing', 'Cascade'),
  ('Flexi + stahlregen - jelly showoff parade', 'Gelatine'),
  ('Flexi - alien fish pond', 'Abyssal'),
  ('Flexi - area 51', 'Xenon'),
  ('flexi - bouncing balls [double mindblob neon mix]', 'Ricochet'),
  ('Flexi - infused with the spiral', 'Helix'),
  ('Flexi - mindblob [shiny mix]', 'Mindblob'),
  ('Flexi - mindblob mix', 'Synapse'),
  ('flexi - mom, why the sky looks different today', 'Skyfall'),
  ('flexi - patternton, district of media, capitol of the united abstractions of fractopia', 'Fractopia'),
  ('Flexi - predator-prey-spirals', 'Predator'),
  ('Flexi - smashing fractals [acid etching mix]', 'Acidmelt'),
  ('flexi - swing out on the spiral', 'Vortex'),
  ('Flexi - truly soft piece of software - this is generic texturing (Jelly) ', 'Velvet'),
  ('flexi - what is the matrix', 'Matrix'),
  ('Flexi, fishbrain, Geiss + Martin - tokamak witchery', 'Tokamak'),
  ('Flexi, martin + geiss - dedicated to the sherwin maxawow', 'Sherwin'),
  ('Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b', 'Supernova'),
  ('Geiss + Flexi + Martin - disconnected', 'Severance'),
  ('Geiss - Cauldron - painterly 2 (saturation remix)', 'Cauldron'),
  ('Geiss - Reaction Diffusion 2', 'Diffusion'),
  ('Geiss - Spiral Artifact', 'Artifact'),
  ('Geiss - Thumb Drum', 'Drumbeat'),
  ('Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]', 'Crossfire'),
  ('Goody - The Wild Vort', 'Wildvort'),
  ('high-altitude basket unraveling - singh grooves nitrogen argon nz+', 'Nitrogen'),
  ('Idiot - Star Of Annon', 'Annon'),
  ('Krash + Illusion - Spiral Movement', 'Spiralwave'),
  ('martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained', 'Diamond'),
  ('Martin - acid wiring', 'Acidwire'),
  ('martin - angel flight', 'Seraph'),
  ('martin - another kind of groove', 'Groove'),
  ('martin - bombyx mori', 'Silkworm'),
  ('martin - castle in the air', 'Skycastle'),
  ('martin - chain breaker', 'Chainbreak'),
  ('Martin - charisma', 'Charisma'),
  ('martin - disco mix 4', 'Discoball'),
  ('martin - extreme heat', 'Inferno'),
  ('martin - frosty caves 2', 'Frostcave'),
  ('martin - fruit machine', 'Jackpot'),
  ('martin - ghost city', 'Phantom'),
  ('martin - glass corridor', 'Glasswalk'),
  ('martin - infinity (2010 update)', 'Infinity'),
  ('Martin - liquid arrows', 'Liquidbow'),
  ('martin - mandelbox explorer - high speed demo version', 'Mandelbox'),
  ('martin - mucus cervix', 'Viscera'),
  ('Martin - QBikal - Surface Turbulence IIb', 'Turbulence'),
  ('martin - reflections on black tiles', 'Blacktile'),
  ('martin - stormy sea (2010 update)', 'Tempest'),
  ('martin - The Bridge of Khazad-Dum', 'Khazaddum'),
  ('martin - witchcraft reloaded', 'Witchfire'),
  ('martin [shadow harlequins shape code] - fata morgana', 'Mirage'),
  ('martin, flexi, fishbrain + sto - enterstate [random mashup]', 'Enterstate'),
  ('Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX', 'Cosmos'),
  ('ORB - Waaa', 'Warpcry'),
  ('Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix', 'Mandala'),
  ('Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)', 'Fractaldrop'),
  ('Rovastar - Oozing Resistance', 'Ooze'),
  ('sawtooth grin roam', 'Sawtooth'),
  ('shifter - dark tides bdrv mix 2', 'Darktide'),
  ('suksma - heretical crosscut playpen', 'Heretic'),
  ('suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression', 'Sunflare'),
  ('suksma - uninitialized variabowl (hydroponic chronic)', 'Hydra'),
  ('suksma - vector exp 1 - couldn′t not', 'Vector'),
  ('TonyMilkdrop - Leonardo Da Vinci''s Balloon [Flexi - merry-go-round + techstyle]', 'Davinci'),
  ('TonyMilkdrop - Magellan''s Nebula [Flexi - you enter first + multiverse]', 'Magellan'),
  ('Unchained & Rovastar - Wormhole Pillars (Hall of Shadows mix)', 'Wormhole'),
  ('Unchained - Rewop', 'Rewop'),
  ('Unchained - Unified Drag 2', 'Dragforce'),
  ('yin - 191 - Temporal singularities', 'Singularity'),
  ('Zylot - Paint Spill (Music Reactive Paint Mix)', 'Paintspill'),
  ('Zylot - Star Ornament', 'Starforge'),
  ('Zylot - True Visionary (Final Mix)', 'Visionary')
ON CONFLICT (original_name) DO UPDATE SET display_name = EXCLUDED.display_name;
